### ISSUE TITLE
Create JSON Storage DB Table

### ISSUE THREAD

**Issue by javenlalla** [javenlalla/my-reddit-archiver#16]
# Overview

In lieu of caching, a database table should exist to store the full JSON bodies of Reddit items. This table is meant to sit in front of API calls as a primary look-up by Reddit ID prior to executing a call against the Reddit API.

# Task

- [x] Create a database table, Entity, and Repository to store Reddit Items JSON bodies (https://github.com/javenlalla/my-reddit-archiver/commit/f83ed8d45e6f2f861f43dcfb4443a01e7a46c7e9)
- [x] Implement logic to look up Reddit items by their Reddit IDs in the new DB table prior to API calls (https://github.com/javenlalla/my-reddit-archiver/commit/f0cb357aec143fc450854bcf0a1ea9526171866c)
- [x] Implement logic to store JSON bodies after a successful Reddit API response (https://github.com/javenlalla/my-reddit-archiver/commit/f0cb357aec143fc450854bcf0a1ea9526171866c)
- [x] Update Item Info fetch logic in the `Manager` Service to leverage the new look-up logic in-front of the API calls (7147ed377885c3e5da1c6fc1407fa4852bdce59e, 28516e57a9041389c329b928bc0a6627e4531530)
- [x] Remove Item Info caching logic in API calls (the cache logic within the API Service class) (c56db7226c73b61b2fcbf054d1e9680211c72e55)
