### ISSUE TITLE
Remove Full Comments Syncing Logic

### ISSUE THREAD

**Issue by javenlalla** [javenlalla/my-reddit-archiver#22]
# Overview

A lot of the current Comment syncing logic operates in the realm of automated syncing to sync many (and in some cases _all_) Comments from a Post. This results in an increase in unexpected calls against the Reddit API and the API's rate limit.

Comments syncing should no longer traverse entire Comment trees and should only sync the target Comment alone.

Further syncing of Comments within the tree will be handled in later work by allowing the action to be manually user-triggered (within the UI, for example).

# Task

Refactor the Comments syncing logic to address the following:

- [x] All Comments logic should rely on the Item Info `Service` look-up
- [x] Remove logic in which Comment trees (both root and children) are traversed and sync'd 
- [x] Refactor tests in the `CommentsSyncTest` to verify the updated use cases per this ticket
